In [8]:
import numpy as np

#dimenesions entered by a user
rows = int(input('Enter the number of rows: '))
columns = int(input('Enter the number of columns: '))

#create list of lists using nested for loops
the_list = []
for i in range(rows):
    row = []
    for j in range(columns):
        value = np.random.randint(0, 100)
        row.append(value)
    the_list.append(row)

# Convert the list of lists to a NumPy array
numpy_array = np.array(the_list)

# Output the result
print("\nList of lists:")
print(the_list)

print("\nConverted NumPy array:")
print(numpy_array)


List of lists:
[[6, 40, 97, 83, 28], [9, 60, 2, 45, 8], [64, 23, 42, 29, 7], [98, 59, 97, 25, 96], [78, 91, 30, 48, 67], [8, 34, 35, 96, 8], [23, 51, 60, 26, 35], [13, 34, 82, 68, 18]]

Converted NumPy array:
[[ 6 40 97 83 28]
 [ 9 60  2 45  8]
 [64 23 42 29  7]
 [98 59 97 25 96]
 [78 91 30 48 67]
 [ 8 34 35 96  8]
 [23 51 60 26 35]
 [13 34 82 68 18]]
